### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lucasgrocha** [lucasgrocha/InternSpot#2]
>Back-end
- [ ] Update record according the spot day
          (e.g): If a spot gets created today, every new spots will update instead of create a new record.

- [ ] Export records as (CSV, spreadsheet)

> Front-end

- [ ]  The buttons disappear as they are registered.
- [ ] Logout button
